=== stefanreuther/c2ng/scripts/pcc2help.dtd
<!ENTITY nbsp "&#160;">

<!ENTITY % block "h1|h2|h3|p|ul|ol|kl|dl|img|table|pre">
<!ENTITY % text  "#PCDATA|a|b|em|tt|kbd|font|small|big|u">
<!ENTITY % nestedBlock "ul|ol|kl|dl|img|br|table|pre">

<!-- Help system entry points -->
<!ELEMENT help (page|group)*>
<!ATTLIST help priority CDATA #IMPLIED>

<!ELEMENT group (page|group)*>
<!ATTLIST group id    CDATA #IMPLIED
                title CDATA #REQUIRED>

<!ELEMENT page (%block;|page)*>
<!ATTLIST page id CDATA #REQUIRED>

<!-- Download area entry points -->
<!ELEMENT fileset (dir|file)*>

<!ELEMENT dir (%block;|dir|file)*>
<!ATTLIST dir id    CDATA #REQUIRED
              title CDATA #IMPLIED
              tag   CDATA #IMPLIED
              date  CDATA #IMPLIED>

<!ELEMENT file EMPTY>
<!ATTLIST file src   CDATA #REQUIRED
               name  CDATA #IMPLIED
               title CDATA #IMPLIED
               tag   CDATA #IMPLIED
               date  CDATA #IMPLIED>

<!-- Headings originally contain only #PCDATA to allow reusing them in attributes -->
<!-- Enable <em> because that has been used extensively in the script manual for ages -->
<!ELEMENT h1     (#PCDATA|em)*>
<!ELEMENT h2     (#PCDATA|em)*>
<!ELEMENT h3     (#PCDATA|em)*>
<!ATTLIST h1 id CDATA #IMPLIED>
<!ATTLIST h2 id CDATA #IMPLIED>
<!ATTLIST h3 id CDATA #IMPLIED>

<!-- Generic paragraph -->
<!ELEMENT p      (%text;|img|br)*>

<!-- ul/ol contain any number of li -->
<!ELEMENT ul     (li)*>
<!ELEMENT ol     (li)*>
<!ELEMENT li     (%text;|%nestedBlock;)*>
<!ATTLIST ul class CDATA #IMPLIED>
<!ATTLIST ol class CDATA #IMPLIED>
<!ATTLIST li bullet CDATA #IMPLIED>

<!-- kl contains any number of <ki key="...">...</ki> -->
<!ELEMENT kl     (ki)*>
<!ELEMENT ki     (%text;|%nestedBlock;)*>
<!ATTLIST ki key CDATA #REQUIRED>

<!-- dl contains any number of <di term="...">...</di> -->
<!ELEMENT dl     (di)*>
<!ELEMENT di     (%text;|%nestedBlock;)*>
<!ATTLIST di term CDATA #REQUIRED>

<!-- Text elements can nest as required -->
<!-- Links -->
<!ELEMENT a      (%text;)*>
<!ATTLIST a href CDATA #REQUIRED>

<!-- Font styles -->
<!ELEMENT b      (%text;)*>
<!ELEMENT u      (%text;)*>
<!ELEMENT em     (%text;)*>
<!ELEMENT tt     (%text;)*>
<!ELEMENT font   (%text;)*>
<!ATTLIST font color CDATA #IMPLIED>
<!ELEMENT small  (%text;)*>
<!ELEMENT big    (%text;)*>

<!-- Keycaps. These do not nest. -->
<!ELEMENT kbd    (#PCDATA)>

<!-- Images -->
<!ELEMENT img    EMPTY>
<!ATTLIST img src   CDATA #REQUIRED
              align (left|right|center) #IMPLIED>

<!-- Hard linefeed -->
<!ELEMENT br     EMPTY>

<!-- Tables -->
<!ELEMENT table  (tr)*>
<!ATTLIST table align (left|right|center) #IMPLIED>

<!ELEMENT tr     (td|tn|th)*>

<!-- Table cells. td is regular data, th is heading (highlighted, centered),
     tn is numbers (right-aligned). Alignment can be overridden. Widths
     can and must be specified on the first line. -->
<!ELEMENT td     (%text;)*>
<!ELEMENT th     (%text;)*>
<!ELEMENT tn     (%text;)*>
<!ATTLIST td align (left|right|center) #IMPLIED   width CDATA #IMPLIED>
<!ATTLIST th align (left|right|center) #IMPLIED   width CDATA #IMPLIED>
<!ATTLIST tn align (left|right|center) #IMPLIED   width CDATA #IMPLIED>

<!-- Preformatted -->
<!ELEMENT pre    (%text;)*>
<!ATTLIST pre class (plaintext|ccscript) #IMPLIED>

=== stefanreuther/c2ng/share/resource/pcc2help.xml
<?xml version="1.0"?>
<!DOCTYPE help SYSTEM "pcc2help.dtd">
<help priority="99">
  <!-- Main TOC -->
  <page id="toc">
    <h1>PCC2 Help Table of Content</h1>
    <ul>
      <li>Startup
      <ul>
        <li><a href="pcc2:invoke">Invoking PCC2</a>;</li>
        <li><a href="config:intro">Configuration files</a>.</li>
      </ul></li>
      <li>Using
      <ul>
        <li><a href="pcc2:gamesel">Game Selection</a>;</li>
        <li><a href="pcc2:racescreen">Race Screen</a>;</li>
        <li><a href="pcc2:cscreen">Control Screen</a>;</li>
        <li><a href="pcc2:starchart">Starchart</a>;</li>
        <li><a href="pcc2:bsim">Battle Simulator</a>;</li>
        <li><a href="help">Help</a>.</li>
      </ul></li>
      <li><a href="int:intro">Script Interpreter</a>.</li>
    </ul>
  </page>


  <!-- Invoking -->
  <page id="group:invoking">
    <h1>Invocation</h1>

    <page id="pcc2:invoke">
      <h1>Invoking PCC2</h1>
      <p>PCC2 is a graphical application.
        If you have used the PCC2 Installer, it will have set up an icon for you.
        Otherwise, you will have to start it manually.
        Just starting it (double-click the program) will work, but by passing additional parameters,
        you can customize startup.
        Not counting options, The following possibilities exist:</p>
      <ul>
        <li><tt>c2ng</tt><br />
          (no player number and directory): start with a <a href="pcc2:gamesel">game chooser</a>;</li>
        <li><tt>c2ng GAMEDIR</tt><br />
          start with a <a href="pcc2:gamesel">game chooser</a> in the specified directory.</li>
      </ul>
      <p>You do not have to unpack your RST before playing.
        If you don't, PCC2 will read the RST directly, and produce a TRN directly.
        If you do unpack your turn, PCC2 will behave like a classic VGA Planets&#x2122; client and just modify <tt>.dat</tt> files;
        you will then have to run Maketurn separately.</p>
      <p>To play registered, place a <tt>fizz.bin</tt> file created by your registered client in the game directory,
        just like you do with PCC 1.x.</p>
      <p><tt>c2ng</tt> accepts some command line options as shown below,
        and honors some <a href="env">environment variables</a>.</p>
      <p>The PCC2 Installer for Windows will make a Start Menu shortcut
      which will start PCC2 with a game selector, starting at your Winplan directory.</p>

      <h2>Command-Line Options</h2>
      <ul>
        <li><tt>--bpp=<em>BITS</em></tt>: bits per pixel;</li>
        <li><tt>--fullscreen</tt>: full-screen mode (opposite of <tt>--windowed</tt>);</li>
        <li><tt>--nomousegrab</tt>: don't grab mouse pointer.
          By default, PCC2 grabs the mouse pointer in the starchart to support infinite movement.
          However, this prevents you from switching to another application while in the starchart;</li>
        <li><tt>--password=<em>PASS</em></tt>: result file password;</li>
        <li><tt>--proxy=<em>URL</em></tt>: use proxy for network access. URL can be "socks4://host:port" or "sock5://host:port";</li>
        <li><tt>--resource=<em>NAME</em></tt>: add a resource file;</li>
        <li><tt>--size=<em>WIDTHxHEIGHT</em></tt>: set screen resolution or window size;</li>
        <li><tt>--windowed</tt>: windowed mode (opposite of <tt>--fullscreen</tt>).</li>
      </ul>
    </page>

    <page id="env">
      <h1>Environment Variables</h1>
      <p>The following environment variables are evaluated by PCC2, or by the SDL library it is based upon:</p>
      <ul>
        <li><tt>SDL_VIDEODRIVER</tt>: select a video driver. Possible choices are, depending upon your version of SDL:
          <tt>x11</tt> (Unix: X11),
          <tt>dga</tt> (Unix: XFree DGA),
          <tt>fbcon</tt> (Linux: framebuffer console),
          <tt>svgalib</tt> (Unix: SVGAlib),
          <tt>aalib</tt> (ASCII art, more for fun than actually useful),
          <tt>windib</tt> (Win32: standard GDI),
          <tt>directx</tt> (Win32 DirectX).
        Normally, SDL auto-detects the best driver to use;</li>
        <!-- <li><tt>SDL_AUDIODRIVER</tt>: select an audio driver. Possible choices are, depending upon your version of SDL:
          <tt>alsa</tt> (Linux: ALSA),
          <tt>dma</tt> (Unix: OSS DMA),
          <tt>dsp</tt> (Unix: OSS standard),
          <tt>esd</tt> (Linux: Enlightened sound daemon),
          <tt>waveout</tt> (Win32: standard WaveOut),
          <tt>dsound</tt> (Win32: DirectX).
          Normally, SDL auto-detects the best driver to use;</li> -->
        <li><tt>LC_ALL</tt>, <tt>LC_MESSAGES</tt>, <tt>LANG</tt> (Unix):
          select language. PCC2 uses the first of those variables which is set.
          It should contain a two-letter language code, optionally followed by additional information ignored by PCC2.
          For example, <tt>de</tt> selects German language, like <tt>de_DE</tt>, <tt>de_AT</tt>, <tt>de_DE@utf-8</tt>, etc.;</li>
        <li><tt>HOME</tt> (Unix): your home directory.
          PCC2's <a href="config:intro">configuration directory</a>, <tt>.pcc2</tt>, goes there.</li>
      </ul>
      <p>To change environment variables permanently under Windows NT or higher,
        right-click <em>My Computer</em>, choose <em>Properties</em>, choose
        <em>Advanced</em>, choose <em>Environment Variables</em>, and add the
        variable in the <em>User Variables</em> section.
        Users of other environments put the variables into their startup or login scripts,
        such as <tt>autoexec.bat</tt> or <tt>.profile</tt>.</p>
    </page>
  </page>

  <!-- Screens -->
  <page id="group:screens">
    <h1>PCC2 Screens</h1>

    <!-- Game Selection Screen -->
    <page id="pcc2:gamesel">
      <h1>Game Selection</h1>
      <p>Welcome to PCC2 Next Generation!</p>

      <p><font color="red"><b>Note:</b> The <b>Help</b> key in most of PCC2 is <kbd>Alt-H</kbd>
        (or, where possible, <kbd>H</kbd>),
        not <kbd>F1</kbd> like in many other current desktop programs.
        <kbd>F1</kbd> will work in some screens, but not all.</font></p>

      <p>The Game Selection screen allows you to select a game from your computer, or from a server.
        On top level (labeled "[Places]"), you can either browse into your computer ("My Computer"),
        or into one of the accounts that you created.
        Use <kbd>Ins</kbd> to <a href="pcc2:addaccount">add an account</a>.</p>

      <p>To enter a directory or account, select it on the left and double-click it or press <kbd>Enter</kbd>.
        When looking at a game, available races will be shown on the right.
        Open it for <a href="pcc2:racescreen">playing</a> by double-clicking the race.
        If additional actions are available for a game, choose "Setup &amp; Actions...".</p>

      <kl>
        <ki key="Tab">Switch between fields;</ki>
        <ki key="Left">Switch to directory selector; if already there, go to parent directory;</ki>
        <ki key="Right">Switch to player selector; if not possible, enter directory;</ki>
        <ki key="Enter">On player selector: load game; otherwise like <kbd>Right</kbd>;</ki>
        <ki key="Ins"><a href="pcc2:addaccount">Add account</a>;</ki>
        <ki key="U"><a href="pcc2:unpack">Unpack result files</a>;</ki>
        <ki key="T"><a href="pcc2:resultattachments">Unpack attachments</a>;</ki>
        <ki key="M">Make turn files;</ki>
        <ki key="S"><a href="pcc2:sweep">Clean up directory (sweep)</a>;</ki>
        <ki key="F5"><a href="pcc2:plugins">Plugin Manager</a>;</ki>
        <ki key="ESC">Exit.</ki>
      </kl>

      <p>When a game contains game data, <kbd>Enter</kbd> and <kbd>Right</kbd> will not browse its subdirectories,
        but switch to the game selector instead.
        Normally, game directories do not contain other game directories.
        Use the <em>Change into this folder</em> item at the bottom of the player list
        to browse subdirectories.</p>

        <!-- FIXME: describe additional actions -->

      <h2>Reference</h2>
      <dl>
        <di term="See also:"> <a href="toc">Table of Content</a>, <a href="pcc2:invoke">Invoking PCC2</a>.</di>
      </dl>
    </page>

    <page id="pcc2:addaccount">
      <h1>Add Account</h1>
      <p>PCC2 supports directly talking to hosting servers.
        To do so, you need to tell it your login data.
        You will then be able to browse your games on the server, using PCC2.</p>

      <p>To define an account, enter your user name and choose the server type (PlanetsCentral or planets.nu).
        The account will now appear on the top level of the <a href="pcc2:gamesel">Game Selection screen</a>.</p>

      <h2>Reference</h2>
      <dl>
        <di term="Keys:"><kbd>Ins</kbd> from <a href="pcc2:gamesel">PCC2 Game Selection</a>.</di>
      </dl>
    </page>

    <page id="pcc2:gamedirsetup">
      <h1>Game Directory Setup</h1>

      <p>PCC2 requires a directory to store local data, for example, configuration and history (starchart database).
        When you open a game that has no suitable directory assigned, PCC2 will ask you to provide one.</p>

      <p>Choose between the following possibilities:</p>
      <dl>
        <di term="Automatic"> PCC2 will automatically create a directory in your profile directory
          (<tt>$HOME/.pcc2/games</tt>, <tt>C:\Users\User\AppData\Roaming\PCC2</tt>).
          If you're not planning to use anything other than PCC2, that is a good choice;</di>
        <di term="Manual"> PCC2 will ask you to choose a directory.
          The dialog allows you to pick an existing directory, or create a new one.
          The directory should be empty to not create conflicts with the new data stored by PCC2.
          This is a good choice if you plan to use software other than PCC2 (e.g. VPA, EchoView) as well,
          and need to know exactly how your directory structure is set up;</di>
        <di term="None"> PCC2 will not use a local directory.
